import Head from 'next/head'
import { Certificate, Text } from '@libellum-ds/react'
import { MainLayout } from './layout/MainLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainLayout>        
        <Text type="display" as="div">
          <Certificate/>
          Use Libellum DS - Home
          <Certificate />
        </Text>
      </MainLayout>
    </>
  )
}
